---
title: "flex"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(tidyverse)
library(flexdashboard)
library(p8105.datasets)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Number of items per order on different days of week

```{r}
instacart %>% 
  select(order_id, add_to_cart_order, order_dow) %>% 
  filter(order_id < 80000) %>% 
  group_by(order_id, order_dow) %>% 
  summarise(n_item = n()) %>%
  mutate(order_dow = recode(order_dow, `0` = "Sun", `1` = "Mon", 
                            `2` = "Tue", `3` = "Wed", `4` = "Thu", 
                            `5` = "Fri", `6` = "Sat")) %>% 
  plot_ly(x = ~order_dow, y = ~n_item, type = "box", color = ~order_dow) %>% 
  layout(xaxis = list(title = ""),
         yaxis = list(title = "Number of items ordered"))


```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of orders over time

```{r}
instacart %>%
  select(order_id, order_hour_of_day) %>% 
  distinct(order_id, .keep_all = TRUE) %>% 
  group_by(order_hour_of_day) %>% 
  summarize(n_per_hour = n()) %>% 
  plot_ly(x = ~order_hour_of_day, y = ~n_per_hour, type = "scatter", mode = "lines") %>% 
  layout(xaxis = list(title = "Time(hour)", 
                      tickmode = "array", 
                      tickvals = c(0, 4, 8, 12, 16, 20, 24)), 
         yaxis = list(title = "Order count"))
```

### Histogram for number of days since prior order

```{r}
instacart %>% 
  select(order_id, days_since_prior_order) %>% 
  distinct(order_id, .keep_all = TRUE) %>% 
  plot_ly(x = ~days_since_prior_order, type = "histogram") %>% 
  layout(xaxis = list(title = "Number of days since prior order",
                      tickvals = c(0, 7, 14, 21, 28, 30)))
  
```